# %% Libs:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import scipy as scp

# %% Round2mult function:
def Round2mult(num, mult, method='up'):
    '''
    Round a number to the nearest multiple of a specified value, using ceiling (up) or flooring (down).

    Summary:
    This function takes a number and rounds it to the nearest multiple of a specified value, 
    either rounding up (ceiling) or down (flooring) based on the chosen method.

    Parameters:
    - num (float): The number to be rounded.
    - mult (int or float): The multiple to which 'num' should be rounded.
    - method (str): The rounding method to use ('up' for rounding up, 'down' for rounding down).
                    Default is 'ceil'.

    Returns:
    - float: The nearest multiple of 'mult' based on the specified rounding method.

    Example:
    num_rounded_up = Round2mult(num, mult, method='up')
    num_rounded_down = Round2mult(num, mult, method='down')
    
    Created/Last modified: 2024-11-01
    '''
    if method == 'up':
        return np.ceil(num / mult) * mult
    elif method == 'down':
        return np.floor(num / mult) * mult
    else:
        raise ValueError("Invalid method. Use 'up' or 'down'.")

# %% calculate_cumulative_stats
def calculate_cumulative_stats(data, x, pctls=(25, 50, 75)):
    '''
    Calculate cumulative statistics (energy mean and selected percentiles) for a 2D dataset in dB.

    Summary:
    This function computes the energy-based mean across the second dimension of a
    2D array containing values in dB, converting to linear scale before averaging
    and converting back to dB. It also calculates any user-defined percentiles
    along the same dimension and returns all results in a pandas DataFrame.

    Parameters:
    - data (numpy.ndarray): 2D array with shape (n_points, n_samples), containing
                            values expressed in dB.
    - x (array-like): Independent variable associated with each row of 'data'
                      (e.g., frequency vector).
    - pctls (iterable of int or float): Percentiles to compute. Default is (25, 50, 75).

    Returns:
    - pandas.DataFrame: DataFrame containing:
        * 'Freq_Hz' : Values from 'x'.
        * 'Mean'    : Energy-based mean in dB.
        * 'PCTLxx'  : Requested percentile columns.

    Notes:
    - The mean is always computed and included in the output.
    - Percentiles are calculated directly on the dB values.
    - NaN values are ignored in all calculations.

    Example:
    psd_cum = calculate_cumulative_stats(data=psd,x=fspect,pctls=[25, 50, 75, 90, 95])

    Created/Last modified: 2026-06-12
    '''
    data_cum = {'Freq_Hz': x,'Mean': 10 * np.log10(np.nanmean(10 ** (data / 10), axis=1))}
    for p in pctls:
        data_cum[f'PCTL{p}'] = np.nanpercentile(data, p, axis=1)

    return pd.DataFrame(data_cum)

# %% representate_cumulative_stats function():
def representate_cumulative_stats(data_cum,
                                  ylabel=None,
                                  xmin=None,
                                  xmax=None,
                                  ymin=None,
                                  ymax=None,
                                  FontSize=12,
                                  title_str='',
                                  path2save=None,
                                  filename=None):
    """
    Plot cumulative statistics (Mean and percentiles) versus frequency.

    Summary:
    This function plots the cumulative statistics generated by
    calculate_cumulative_stats(), including the energy-based mean and all
    available percentile curves. The Mean curve is always highlighted, while
    percentile curves are automatically assigned distinguishable colors.

    Parameters:
    - data_cum (pandas.DataFrame): Output DataFrame from
                                   calculate_cumulative_stats().
                                   Must contain columns:
                                   'Freq_Hz', 'Mean', and optional 'PCTLxx'.
    - ylabel (str, optional): Y-axis label.
    - xmin, xmax (float, optional): X-axis limits.
    - ymin, ymax (float, optional): Y-axis limits.
    - FontSize (int, optional): Font size.
    - title_str (str, optional): Plot title.
    - path2save (str, optional): Directory where figure will be saved.
    - filename (str, optional): Figure filename (without extension).

    Notes:
    - Frequencies are plotted in Hz when max frequency ≤ 5 kHz.
    - Frequencies are plotted in kHz when max frequency > 5 kHz.
    - All columns beginning with 'PCTL' are automatically plotted.
    - If the number of percentiles exceeds the predefined color palette,
      additional colors are taken from matplotlib's 'tab20' colormap.

    Created/Last modified: 2026-06-12
    """

    fspect = data_cum['Freq_Hz'].values
    fmax = np.max(fspect)

    if fmax <= 5e3:
        xplot = fspect
        xlabel = 'Frequency [Hz]'
    else:
        xplot = fspect * 1e-3
        xlabel = 'Frequency [kHz]'

    fig, ax = plt.subplots(figsize=(14, 8))

    # Mean curve
    ax.plot(
        xplot,
        data_cum['Mean'],
        color='gold',
        linewidth=3,
        linestyle = '--',
        label='Mean',
        zorder=100
    )

    # Preferred colors
    base_colors = [
        'midnightblue',
        'darkgreen',
        'red',
        'lime',
        'aqua',
        'fuchsia',
        'lightpink'
    ]

    # Detect percentile columns
    pctl_cols = sorted(
        [c for c in data_cum.columns if c.startswith('PCTL')],
        key=lambda x: float(x.replace('PCTL', ''))
    )

    # Extend palette if needed
    if len(pctl_cols) > len(base_colors):
        cmap = plt.get_cmap('tab20')
        extra_colors = [
            cmap(i / (len(pctl_cols) - len(base_colors) + 1))
            for i in range(len(pctl_cols) - len(base_colors))
        ]
        colors = base_colors + extra_colors
    else:
        colors = base_colors

    # Plot percentiles
    for col, color in zip(pctl_cols, colors):
        ax.plot(
            xplot,
            data_cum[col],
            color=color,
            linewidth=1.5,
            label=col
        )

    # Labels
    ax.set_xlabel(xlabel, fontsize=FontSize)

    if ylabel is not None:
        ax.set_ylabel(ylabel, fontsize=FontSize)

    # Limits
    if xmin is not None or xmax is not None:
        ax.set_xlim(
            xmin if xmin is not None else ax.get_xlim()[0],
            xmax if xmax is not None else ax.get_xlim()[1]
        )

    if ymin is not None or ymax is not None:
        ax.set_ylim(
            ymin if ymin is not None else ax.get_ylim()[0],
            ymax if ymax is not None else ax.get_ylim()[1]
        )

    # Title
    if title_str:
        ax.set_title(title_str, fontsize=FontSize + 2)

    ax.grid(True)

    ax.legend(
        ncol=min(4, len(pctl_cols) + 1),
        loc='upper center',
        fontsize=FontSize - 2
    )

    ax.tick_params(axis='both', which='major', labelsize=FontSize)
    ax.tick_params(axis='both', which='minor', labelsize=FontSize)

    plt.tight_layout()

    # Save
    if path2save is not None and filename is not None:
        os.makedirs(path2save, exist_ok=True)
        plt.savefig(
            os.path.join(path2save, filename + '.png'),
            bbox_inches='tight',
            dpi=150
        )

    plt.show()

# %% fs_factor function(): 
def fs_factor(fs, fmax_sel):
    '''
    Calculates the down-sampling factor to meet the maximum frequency constraint (fmax_sel).

    Parameters:
    - fs (float): Original sampling frequency [Hz].
    - fmax_sel (float): Maximum selected frequency [Hz].

    Returns:
    - factor (int): Down-sampling factor to achieve a maximum frequency below fmax_sel.
    - fs_new (float): Adjusted sampling frequency after down-sampling [Hz].

    Application:
    factor, fs_new = fs_factor(fs, fmax_sel)
    
    Created/Last modified: 2024-04-05
    '''
    # Function implementation goes here
    fs_new = fs
    factor = 1
    while fs_new / 2 >= fmax_sel:
        factor += 1
        fs_new = fs / factor
    if fs_new / 2 < fmax_sel:
        factor -= 1
        fs_new = fs / factor

    return factor, fs_new

# %% dBsum function:
def dBsum(dBs, log_base=10, axis=0):
    '''
    Calculate the sum of an array of dB values in the logarithmic domain, supporting multi-dimensional arrays.

    Summary:
    This function converts an array of dB values to the linear scale, computes their sum along the specified axis,
    and converts the result back to dB. The `log_base` parameter allows flexibility for different types of dB calculations 
    (e.g., power ratio with log_base=10 or sound pressure with log_base=20).

    Parameters:
    - dBs (numpy.ndarray): An array of decibel values to be summed.
    - log_base (int or float): The logarithm base to use for the conversion. Default is 10.
    - axis (int): The axis along which to compute the sum. Default is 0 (sum across columns).

    Returns:
    - numpy.ndarray: The sum value in decibels along the specified axis.

    Example:
    total_dB = dBsum(np.array([60, 62, 58, 61]), log_base=20) # For 1D array
    total_dB = dBsum(np.array([[60, 62], [58, 61]]), log_base=20, axis=0) # For 2D array

    Created/Last modified: 2024-12-14
    '''
    # Convert the dB values to linear scale
    linear_values = 10 ** (dBs / log_base)
    
    # Compute the sum along the specified axis
    linear_sum = np.sum(linear_values, axis=axis)
    
    # Convert the result back to dB
    return log_base * np.log10(linear_sum)

# %% 
def curveReaderPSDdataCum(csv_file, column='Mean'):
    """
    Lee PSDdata_cum.csv y devuelve frecuencia y la curva seleccionada.

    Parameters
    ----------
    csv_file : str
        Ruta al CSV.
    column : str
        'Mean', 'PCTL25', 'PCTL50', 'PCTL75', 'PCTL90' o 'PCTL95'.

    Returns
    -------
    freq : np.ndarray
        Frecuencias (Hz).
    psd : np.ndarray
        Valores de la columna seleccionada.
    """
    
    df = pd.read_csv(csv_file, sep=';')

    if column not in df.columns:
        raise ValueError(
            f"'{column}' no existe. Opciones: {list(df.columns[1:])}"
        )

    freq = df['Freq_Hz'].to_numpy()
    psd = df[column].to_numpy()

    return freq, psd

# %% low_pass_filter function():
def low_pass_filter(signal, cutoff_freq, sample_rate, order=4):
    """
    Apply a zero-phase Butterworth low-pass filter.

    Parameters
    ----------
    signal : ndarray
        Input signal.
    cutoff_freq : float
        Low-pass cutoff frequency [Hz].
    sample_rate : float
        Sampling frequency [Hz].
    order : int, optional
        Filter order.

    Returns
    -------
    ndarray
        Filtered signal.
    """
    nyquist = 0.5 * sample_rate
    normalized_cutoff = cutoff_freq / nyquist

    b, a = scp.signal.butter(
        order,
        normalized_cutoff,
        btype="low"
    )

    return scp.signal.filtfilt(b, a, signal)